.PHONY: main tut

main:
	pdflatex policy.tex
	pdflatex policy.tex
	pdflatex policy.tex

tut:
	pdflatex 10350_tutorwk01_solutions.tex
	pdflatex 10350_tutorwk01_solutions.tex
	pdflatex 10350_tutorwk01_solutions.tex

clean:
	rm *.aux
	rm *.log
