.PHONY: syllabus revision slides

slides:
	pdflatex slides.tex
	pdflatex slides.tex
	pdflatex slides.tex

syllabus:
	pdflatex syllabus.tex
	pdflatex syllabus.tex
	pdflatex syllabus.tex

revision:
	pdflatex revision.tex
	pdflatex revision.tex
	pdflatex revision.tex

clean:
	rm *.aux
	rm *.log
