.PHONY: syllabus slides

slides:
	pdflatex slides.tex
	pdflatex slides.tex
	pdflatex slides.tex

syllabus:
	pdflatex syllabus.tex
	pdflatex syllabus.tex
	pdflatex syllabus.tex

clean:
	rm *.aux
	rm *.log
